//
// Created by Olcay Taner YILDIZ on 16.11.2023.
//

#ifndef ANNOTATEDSENTENCE_VIEWLAYERTYPE_H
#define ANNOTATEDSENTENCE_VIEWLAYERTYPE_H

enum view_layer_type{
    PART_OF_SPEECH, INFLECTIONAL_GROUP, META_MORPHEME, META_MORPHEME_MOVED, TURKISH_WORD, PERSIAN_WORD, ENGLISH_WORD, WORD, SEMANTICS, NER, DEPENDENCY, PROPBANK, SHALLOW_PARSE, ENGLISH_PROPBANK, ENGLISH_SEMANTICS, FRAMENET, SLOT, POLARITY, CCG, POS_TAG
};

typedef enum view_layer_type View_layer_type;

#endif //ANNOTATEDSENTENCE_VIEWLAYERTYPE_H
